### ISSUE TITLE
Add the let-it-snow plugin for the festive season

### ISSUE THREAD

**Issue by inezabonte** [queen-raae/nattermob.dev#57]
I'd be happy to contribute to this repo by adding the let-it-snow plugin by Raae if you want.
Share with me the color combinations you'd like and I'll create a PR 😊

**Comment by raae** [comment]
I trust you to come up with a nice combo. Or you can steal the one from Paul's personal site.

**Comment by inezabonte** [comment]
Uuhh, Okay 😄. I'll get to it
