### ISSUE TITLE
Add accent color to markdown links

### ISSUE THREAD

**Issue by inezabonte** [queen-raae/nattermob.dev#62]
The markdown styled by tailwind has a plain styling.
The pages would look more vibrant if the links had the same "queen-red" color
used on the homepage.
<img width="946" alt="Screen Shot 2021-12-24 at 19 01 56" src="https://user-images.githubusercontent.com/33348046/147366028-22d64ea7-0d59-4e54-b27e-27ff1c7a3f32.png">

**Comment by inezabonte** [comment]
I'd be happy to add it if you want.

**Comment by inezabonte** [comment]
@raae

**Comment by raae** [comment]
Feel free! 
It's been a little activity here since @PaulieScanlon joined Gatsby 😬
